services:
  postgresql:
    container_name: postgresql
    image: postgres:12.13-alpine3.17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: furniture